### ISSUE TITLE
Firefox Pop Up doesn't shows up

### ISSUE THREAD

**Issue by rizwan2000rm** [Purhan/dotfiles#1]
As you can see the Firefox has 2 icons on the titlebar, one is the browser and second is the popup for the master password of the browser. But the popup actually doesn't show up in any window configuration.

I don't know why is this happening or is this has to even do anything with your configs

![image.png](https://user-images.githubusercontent.com/48753482/92508532-6c6d4180-f226-11ea-8e29-6ca800e4d320.png)

**Comment by purhan** [comment]
Hi, could you explain what you mean by "master password of the web browser"?
It's possible that the policykit daemon is not working. Please check which daemon is listed in [$AWESOME_CONFIG/configuration/apps.lua](https://github.com/Purhan/dotfiles/blob/master/RICE/werewolf/configuration/apps.lua) and make sure you have that installed.

**Comment by rizwan2000rm** [comment]
It is just like a notification pop up which doesn't shows up on screen for some reason. It is very small in size, so I tried floating windows still no luck. I still can type my password in it and press enter though.

**Comment by rizwan2000rm** [comment]
Same thing happens for New Folder Pop Up in Dolphin doesn't show up on the screen, but I can type the name of folder and it creates it.

**Comment by Purhan** [comment]
Are you experiencing this issue on other applications too?

Here is a screenshot of a popup on Pamac, this would work only if the policykit is running. Does this work as intended for you?
![image](https://user-images.githubusercontent.com/10897423/92510170-0afaa200-f229-11ea-8a45-7e024d81163e.png)

**Comment by purhan** [comment]
> Same thing happens for New Folder Pop Up in Dolphin doesn't show up on the screen, but I can type the name of folder and it creates it.

I have two questions.
1. What version of Awesome are you using?
2. What happens when you comment out rules for "**type = {'dialog'}**" in [$AWESOME_CONFIG/configuration/client/rules.lua](https://github.com/Purhan/dotfiles/blob/master/RICE/werewolf/configuration/client/rules.lua) ?

**Comment by rizwan2000rm** [comment]
I think it's the polkit, for some reason it doesn't start on startup.

**Comment by rizwan2000rm** [comment]
I have installed kde polkit agent and also corrected the path of it in the configs. It still doesn't loads at boot I don't know what is wrong with it. Also tried xfce and gnome polkit no luck their either.

**Comment by rizwan2000rm** [comment]
Woah commenting the line you mentioned worked now I can see the pop up notification. Thanks for the help.
