### ISSUE TITLE
System tray icons not displaying

### ISSUE THREAD

**Issue by wildebeest3** [Purhan/dotfiles#4]
The system tray icons are not displayed at all. I'm not sure if it's an issue with the svg icons.

**Comment by purhan** [comment]
@wildeb33st could you include a screenshot please?

**Comment by wildebeest3** [comment]
Please see attached image. 
![1606242278](https://user-images.githubusercontent.com/74982370/100158612-d7700100-2e82-11eb-872a-c7c98b94ccf6.png)

**Comment by ramezhammad** [comment]
bump :D
