### ISSUE TITLE
Bars arent displayed right on second monitor

### ISSUE THREAD

**Issue by ghost** [Purhan/dotfiles#5]
Hello,
as you can see on the screenshot below, the bars are kinda messed up on my second monitor. Problem is probably because its 4:3 and the resolution is 1280x1024, so not a normal resolution. So, how can i fix this?
![Screenshot_20201228_120255](https://user-images.githubusercontent.com/66372470/103210097-f986f400-4904-11eb-9ccb-f36a70dd66ac.png)

**Comment by purhan** [comment]
@Azandigo Hi, have you tried reloading Awesome after connecting your second monitor? (Ctrl + Super + r)

**Comment by ghost** [comment]
@Purhan Wow, youre answering really quick! Yes, ive done several reloads of awesome because of the changes i did.
Edit: Ive tried it with the default config, issue still appearing

**Comment by purhan** [comment]
@Azandigo I'd recommend using some tool like ARandr to manage the resolution of your monitors. I use an external monitor myself and this is what I use. You could export the settings as a bash script and run them on startup to avoid doing it yourself everytime.

**Comment by ghost** [comment]
@Purhan I dont really understand that. Changing the resolution or using an tool doesnt help. I just use nvidia-settings and that saves it to the xorg conf, i dont have to do it everytime by myself. Ive tried arandr, but no matter what resolution i would choose the bars are still like they are on the screenshot.
